# -*- coding: utf-8 -*-
"""python_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SVs9nPHHHleVbvEMCDHx55Qg-hQqnh9i
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pandas.tseries.offsets import BDay

#Sumber data yang digunakan
path_od = "https://raw.githubusercontent.com/dataskillsboost/FinalProjectDA11/main/order_detail.csv"
path_pd = "https://raw.githubusercontent.com/dataskillsboost/FinalProjectDA11/main/payment_detail.csv"
path_cd = "https://raw.githubusercontent.com/dataskillsboost/FinalProjectDA11/main/customer_detail.csv"
path_sd = "https://raw.githubusercontent.com/dataskillsboost/FinalProjectDA11/main/sku_detail.csv"
df_od = pd.read_csv(path_od)
df_pd = pd.read_csv(path_pd)
df_cd = pd.read_csv(path_cd)
df_sd = pd.read_csv(path_sd)

#Mengampilkan 5 baris pertama
df_od.head()

#Mengampilkan 5 baris pertama
df_pd.head()

#Mengampilkan 5 baris pertama
df_cd.head()

#Mengampilkan 5 baris pertama
df_sd.head()

#Menjalankan SQL di Colab
from sqlite3 import connect
conn = connect(':memory:')
df_od.to_sql('order_detail',conn, index=False, if_exists='replace')
df_pd.to_sql('payment_detail', conn, index=False, if_exists='replace')
df_sd.to_sql('sku_detail', conn, index=False, if_exists='replace')
df_cd.to_sql('customer_detail', conn, index=False, if_exists='replace')

#Query SQL untuk menggabungkan data
df = pd.read_sql("""
SELECT
    order_detail.*,
    payment_detail.payment_method,
    sku_detail.sku_name,
    sku_detail.base_price,
    sku_detail.cogs,
    sku_detail.category,
    customer_detail.registered_date
FROM order_detail
LEFT JOIN payment_detail
    on payment_detail.id = order_detail.payment_id
LEFT JOIN sku_detail
    on sku_detail.id = order_detail.sku_id
LEFT JOIN customer_detail
    on customer_detail.id = order_detail.customer_id
""", conn)

#Mengampilkan 5 baris pertama
df.head()

#Menampikan tipe data tiap kolom
df.dtypes

#Mengubah tipe data agar mudah dilakukan pengolahan data
df = df.astype({"before_discount":'int', "discount_amount":'int', "after_discount":'int',"base_price":'int'})
df.dtypes

#Mengubah tipe kolom Date menjadi Datetime
df['order_date']= pd.to_datetime(df['order_date'])
df['registered_date']= pd.to_datetime(df['registered_date'])
df.dtypes

"""## `No 1`
**Dear Data Analyst**,
<br></br>
Akhir tahun ini, perusahaan akan memberikan hadiah bagi pelanggan yang memenangkan kompetisi **Festival Akhir Tahun**. Tim Marketing membutuhkan bantuan untuk menentukan perkiraan hadiah yang akan diberikan pada pemenang kompetisi nantinya. Hadiah tersebut akan diambil dari **TOP 5 Produk** dari Kategori **Mobiles & Tablets** selama tahun 2022, dengan jumlah kuantitas penjualan (valid = 1) paling tinggi.

Mohon bantuan, untuk mengirimkan data tersebut sebelum akhir bulan ini ke Tim Marketing. Atas bantuan yang diberikan, kami mengucapkan terima kasih.
<br></br>
Regards

**Tim Marketing**

## `Jawaban No 1`
"""

# 1. Filter for valid transactions (is_valid = 1)
df_valid = df[df['is_valid'] == 1]

# 2. Filter for 'Mobiles & Tablets' category
df_mobile_table_tablets = df_valid[df_valid['category'] == 'Mobiles & Tablets']

# 3. Filter for transactions in the year 2022
df_2022_mobile_tablets = df_mobile_table_tablets[df_mobile_table_tablets['order_date'].dt.year == 2022]

# 4. Group by sku_name and sum qty_ordered
top_products = df_2022_mobile_tablets.groupby('sku_name')['qty_ordered'].sum().reset_index()

# 5. Sort by quantity ordered in descending order
top_products_sorted = top_products.sort_values(by='qty_ordered', ascending=False)

# 6. Get the top 5 products
top_5_mobile_tablets = top_products_sorted.head(5)

print("Top 5 Products in 'Mobiles & Tablets' Category (2022, Valid Sales) by Quantity:")
display(top_5_mobile_tablets)

"""## `No 2`
**Dear Data Analyst**,
<br></br>
Menindaklanjuti meeting gabungan Tim Werehouse dan Tim Marketing, kami menemukan bahwa ketersediaan stock produk dengan Kategori Others pada akhir 2022 kemarin masih banyak.
1. Kami mohon bantuan untuk melakukan pengecekan data penjualan kategori tersebut dengan tahun 2021 secara kuantitas penjualan. Dugaan sementara kami, telah terjadi penurunan kuantitas penjualan pada 2022 dibandingkan 2021. (Mohon juga menampilkan data ke-15 kategori)
<br></br>
2. Apabila memang terjadi penurunan kuantitas penjualan pada kategori Others, kami mohon bantuan untuk menyediakan data TOP 20 nama produk yang mengalami penurunan paling tinggi pada 2022 jika dibanding dengan 2021. Hal ini kami gunakan sebagai bahan diskusi pada meeting selanjutnya.  

Mohon bantuan untuk mengirimkan data tersebut paling lambat 4 hari dari hari ini. Atas bantuan yang diberikan, kami mengucapkan terima kasih.
<br></br>
Regards

**Tim Werehouse**

## `Jawaban No 2.1`
"""

df['year'] = df['order_date'].dt.year

others = df[(df['category'] == 'Others') & (df['is_valid'] == 1)]

others_yearly = (
    others
    .groupby('year')['qty_ordered']
    .sum()
    .loc[[2021, 2022]]
    .reset_index(name="Total Quantity")
)

print("Perbandingan Penjualan Kategori Others (2021 vs 2022):")
display(others_yearly)

top15_others = (
    others[others['year'] == 2022]
    .groupby('sku_name')['qty_ordered']
    .sum()
    .sort_values(ascending=False)
    .head(15)
    .reset_index(name="Total Quantity")
)

print("\nTOP 15 Produk Kategori Others Tahun 2022:")
display(top15_others)

"""## `Jawaban No 2.2`"""

df['order_date'] = pd.to_datetime(df['order_date'])

df_others = df[
    (df['is_valid'] == 1) &
    (df['category'] == 'Others') &
    (df['order_date'].dt.year.isin([2021, 2022]))
]

df_2021 = df_others[df_others['order_date'].dt.year == 2021]
df_2022 = df_others[df_others['order_date'].dt.year == 2022]

sales_2021 = df_2021.groupby('sku_name')['qty_ordered'].sum().reset_index()
sales_2021.rename(columns={'qty_ordered': 'qty_2021'}, inplace=True)

sales_2022 = df_2022.groupby('sku_name')['qty_ordered'].sum().reset_index()
sales_2022.rename(columns={'qty_ordered': 'qty_2022'}, inplace=True)

df_compare = pd.merge(sales_2021, sales_2022, on='sku_name', how='outer').fillna(0)

df_compare['penurunan'] = df_compare['qty_2022'] - df_compare['qty_2021']

top20 = df_compare.sort_values('penurunan').head(20)

print(top20)

"""## `No 3`
**Dear Data Analyst**,
<br></br>
Terkait ulang tahun perusahaan pada 2 bulan mendatang, Tim Digital Marketing akan memberikan informasi promo bagi pelanggan pada akhir bulan ini. Kriteria pelanggan yang akan kami butuhkan adalah mereka yang sudah melakukan check-out namun belum melakukan pembayaran (is_gross = 1) selama tahun 2022. Data yang kami butuhkan adalah ID Customer dan Registered Date.

Mohon bantuan, untuk mengirimkan data tersebut sebelum akhir bulan ini ke Tim Digital Marketing. Atas bantuan yang diberikan, kami mengucapkan terima kasih.
<br></br>
Regards

**Tim Digital Marketing**
"""

# Tulis kode Anda di bawah ini. Dapat menggunakan lebih dari 1 blok kode

# step 1 - memfilter data sesuai kriteria
# pelanggan yang belum melakukan payment (is_gross = 1) selama tahun 2022

# menarik data yang diperlukan
df_tokopedia = (
    df[
        (df['is_gross'] == 1) &
        (df['is_valid'] == 0) &
        (df['is_net'] == 0) &
        (df['order_date'].dt.year == 2022)
    ]
)

# mengambil data customer_id dan registered date setelah filter data
customer_checkout = (
    df_tokopedia[['customer_id','registered_date']]
    .drop_duplicates()
    .sort_values(by='registered_date')
    .reset_index(drop=True)
)

# menampilkan data
customer_checkout

import matplotlib.pyplot as plt

# klasifikasi customer lama vs baru
customer_checkout['customer_type'] = (
    customer_checkout['registered_date'].dt.year < 2022
).map({True: 'Old Customers (<2022)', False: 'New Customers (2022)'})

# menghitung jumlah masing-masing kategori
customer_counts = customer_checkout['customer_type'].value_counts()

# membuat pie chart
plt.figure(figsize=(6,6))
plt.pie(
    customer_counts,
    labels=customer_counts.index,
    autopct='%1.1f%%',
    startangle=90
)

plt.title('Percentage Old Customers vs New Customers')
plt.show()

"""## `No 4`
**Dear Data Analyst**,
<br></br>
Pada bulan October hingga Desember 2022, kami melakukan campaign setiap hari Sabtu dan Minggu. Kami hendak menilai, apakah campaign tersebut cukup berdampak pada kenaikan penjualan (before_discount). Mohon bantuan untuk menampilkan data:
1. Rata-rata harian penjualan weekends (Sabtu dan Minggu) vs rata-rata harian penjualan weekdays (Senin-Jumat) per bulan tersebut. Apakah ada peningkatan penjualan pada masing-masing bulan tersebut.
2. Rata-rata harian penjualan weekends (Sabtu dan Minggu) vs rata-rata harian penjualan weekdays (Senin-Jumat) keseluruhan 3 bulan tersebut.

Mohon bantuan untuk mengirimkan data tersebut paling lambat minggu depan. Atas bantuan yang diberikan, kami mengucapkan terima kasih.
<br></br>
Regards

**Tim Campaign**
"""

# Ubah kolom tanggal menjadi format datetime
df['order_date'] = pd.to_datetime(df['order_date'])

# Buat kolom hari dan bulan
df['day'] = df['order_date'].dt.day_name()
df['month'] = df['order_date'].dt.month_name()
df['month_num'] = df['order_date'].dt.month

# filter data dengan valid=1
df_valid4 = df[df['is_valid'] == 1].copy()
df_valid4 = df_valid4[(df_valid4['order_date'].dt.year == 2022) &
                      (df_valid4['month_num'].isin([10, 11, 12]))]

# filter data dengan day termasuk 'Monday, Tuesday, Wednesday, Thursday, Friday dengan fungsi isin dan simpan dengan variabel 'weekday)
weekend_days = ['Saturday', 'Sunday']
df_valid4.loc[:, 'day_type'] = df_valid4['day'].apply(lambda x: 'Weekend' if x in weekend_days else 'Weekday')

# gunakan groupby berdasarkan variabel masing-masing
df_daily = df_valid4.groupby(['order_date', 'day_type'], as_index=False)['before_discount'].sum()
df_monthly = df_daily.groupby([df_daily['order_date'].dt.month_name(), 'day_type'])['before_discount'].mean().reset_index()
df_monthly.rename(columns={'before_discount': 'avg_daily_sales'}, inplace=True)

# 1. Filter data valid (menggunakan 'is_valid' yang benar)
df_valid = df[df['is_valid'] == 1]

# 2. Filter periode Oct-Dec 2022
df_period = df_valid[(df_valid['order_date'].dt.year == 2022) &
                     (df_valid['order_date'].dt.month.isin([10,11,12]))]

# 3. Hitung total sales per hari
daily_sales = df_period.groupby(['order_date','day'])['before_discount'].sum().reset_index()

# 4. Pisahkan weekend dan weekday
weekend_daily = daily_sales[daily_sales['day'].isin(['Saturday','Sunday'])]
weekday_daily = daily_sales[daily_sales['day'].isin(['Monday','Tuesday','Wednesday','Thursday','Friday'])]

# 5. Hitung rata-rata harian
avg_weekend = weekend_daily['before_discount'].mean()
avg_weekday = weekday_daily['before_discount'].mean()

# 6. Hitung selisih dan persentase perubahan
diff = avg_weekend - avg_weekday
pct_change = (diff / avg_weekday) * 100

# 7. Tampilkan hasil
print("Overall Performance (Oct-Dec 2022)")
print("-" * 30)
print(f"Rata-rata Harian Weekday: {avg_weekday:,.2f}")
print(f"Rata-rata Harian Weekend: {avg_weekend:,.2f}")
print(f"Kenaikan/Penurunan: {pct_change:.2f}%")

import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import pandas as pd

# Create the overall_avg_sales DataFrame
overall_avg_sales = pd.DataFrame({
    'day_type': ['Weekday', 'Weekend'],
    'overall_avg_daily_sales': [avg_weekday, avg_weekend]
})

plt.figure(figsize=(8, 6))
plt.bar(overall_avg_sales['day_type'], overall_avg_sales['overall_avg_daily_sales'],
        color=['skyblue', 'lightcoral'])

plt.title('Overall Average Daily Sales: Weekday vs. Weekend (Oct-Dec 2022)')
plt.xlabel('Day Type')
plt.ylabel('Average Daily Sales (Before Discount)')

# Format y-axis as currency
formatter = mticker.FuncFormatter(lambda x, p: f'Rp {x:,.0f}'.replace(',', '.'))
plt.gca().yaxis.set_major_formatter(formatter)

# Add text labels on top of the bars
for index, row in overall_avg_sales.iterrows():
    plt.text(row['day_type'], row['overall_avg_daily_sales'],
             f'Rp {row["overall_avg_daily_sales"]:,.0f}'.replace(',', '.'),
             ha='center', va='bottom', fontsize=10)

plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()